ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER oraclequant IDENTIFIED BY oraclequant
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO oraclequant;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO oraclequant;
